### ISSUE TITLE
Homework-9: Pogreshen tip za 'products' i 'shoppingCartProducts' vo ShoppingCartContext.js

### ISSUE THREAD

**Issue by viktorzdravkovski** [BojanMihajlo/Homeworks-React#1]
Vo ShoppingCartContext.js, kade shto go kreirash Context-ot so createContext(), prakjash objekt vo createContext kako parametar koj shto vika deka za products i shoppingCartProducts kje bidat stringovi, a vsushnost tamu cuvame niza od objekti.

**Comment by BojanMihajlo** [comment]
Go popraviv Viktor toa i ke ja ataciram popravena domasnata falaa
