### ISSUE TITLE
Homework-9: Nepotrebni props vo App.js

### ISSUE THREAD

**Issue by viktorzdravkovski** [BojanMihajlo/Homeworks-React#2]
Koga gi renderirash <ProductContainer/> i <ShoppingCartContainer/> vo App.js, seushte gi prakjash kako props produktite i funkciite, iako vnatre vo niv povtorno gi zemash od context-ot, a ne od props. Nema potreba tuka da stojat seushte kako props, i kje moze da se izbrishe celiot useContext hook od App.js

**Comment by BojanMihajlo** [comment]
Da da izbrisav se od App.js i ja popraviv falaa
