### ISSUE TITLE
Homework-5: Input za goals e sekogas so invalid styling

### ISSUE THREAD

**Issue by viktorzdravkovski** [BojanMihajlo/Homeworks-React#3]
Vo Goals.js od Homework-5 probuvas da pristapish do 'props.valid' za da go setirash stilot dinamichki za input poleto, megjutoa 'valid' prop-ot ne go prakjash nikade na <Form> komponentata.
'valid' treba da se prati kako prop na <Form> i da bide true ako vo inputot ima barem eden karakter shto ne e prazno mesto.

**Comment by BojanMihajlo** [comment]
Ja resivme na vezbite vo creative hub ;)
